### PR TITLE
Add npm support for 3.2

### PR DESCRIPTION
**Pull request by ericlemerdy**
Add npm support of last for 3.2.1 (last of 3.2 branch)

Contributes to #29

### CODE REVIEW

**Comment by RobLoach** [comment]
Looks good! If you publish the package, feel free to add a few of the contributors.

**Comment by RobLoach** [comment]
Will also need to be updated to 4.x too.

**Comment by ericlemerdy** [comment]
> If you publish the package, feel free to add a few of the contributors.
You mean contributors of the original `package.json` file, right ? How can I publish the package ? Is it ok to move a tag ?

**Comment by ericlemerdy** [comment]
> Will also need to be updated to 4.x too.

Yes, I am on my way to do it :wink:

**Pull request merged**
